name: meal_tracker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: "^3.5.3"

dependencies:
  flutter:
    sdk: flutter

  # Основні пакети
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.3.3
  connectivity_plus: ^4.0.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
